tasktodo/tasktodo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tasktodo/todoapp/urls.py
from . import views
from django.urls import path
app_name='todoapp'
urlpatterns =  [
    path('',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('cvhome/',views.TaskListview.as_view(),name='cvhome'),
    path('cvdetail/<int:pk>/',views.TaskDetailView.as_view(), name='cvdetail'),
    path('cvupdate/<int:pk>/',views.TaskUpdateView.as_view(), name='cvupdate'),
    path('cvdelete/<int:pk>/',views.TaskDeleteView.as_view(),name='cvdelete'),

]

tasktodo/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task_name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

tasktodo/todoapp/forms.py
from .models import Task
from django import forms
class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['task_name','priority','date']

tasktodo/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from todoapp.forms import TodoForm
from todoapp.models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
# Create your views
class TaskListview(ListView):
    model=Task
    template_name='home.html'
    context_object_name='task1'
class TaskDetailView(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'
class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields=('task_name','priority','date')
    def get_success_url(self):
        return reverse_lazy('todoapp:cvdetail',kwargs={'pk':self.object.id})
class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cvhome')

def add(request):
    task1=Task.objects.all()
    if request.method=='POST':
        task_name=request.POST.get('task_name','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(task_name=task_name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})
def update(request,id):
        task=Task.objects.get(id=id)
        f=TodoForm(request.POST or None,instance=task)
        if f.is_valid():
            f.save()
            return redirect('/')
        return render(request,'edit.html',{'f':f,'task':task})
def delete(request,id):
    task=Task.objects.get(id=id)
    if request.method =='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

tasktodo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
</body>
{% block body %}
{% endblock %}
</html>

tasktodo/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <p> ARE you sure you want to delete this task</p>
    <button type="submit">confirm</button>
</form>

{% endblock %}

tasktodo/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="shadow card">
    <div class="card-body">
        <h5 class="card-title">{{task.task_name}}</h5>'todoapp:delete' task.id
        <p><b></b>{{task.priority}}</p>
        <p><b></b>{{task.date}}</p>
        <a class="btn btn-danger" href="{% url  'todoapp:delete' task.id %}">DELETE</a>
        <a class="btn btn-primary" href="{% url 'todoapp:update' task.id %}">UPDATE</a>

    </div>
</div>
{% endblock %}

tasktodo/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">confirm</button>
</form>
{% endblock %}

tasktodo/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="container"><br><br><br><br>
        <div class="row">
            <div class="col-md-6">
                <form method="POST" class="p-3 shadow">
                 {% csrf_token %}
                <div class="form-group">
                 <input type="text" class="form-control" name="task" placeholder="task name">
                </div>
                <div class="form-group">
                 <input type="text" class="form-control" name="priority" placeholder="priority">
                </div>
                    <div>
                       <input type="date" class="form-control" name="date" placeholder="date">
                 <input type="submit" class="btn btn-success">

                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <h4> Task to be compleated</h4>
                {% for i in task1 %}
                <div class="card">
                    <div class="shadow-sm p-3 mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title">{{i.task_name}}</h5>
                        <p><b>{{i.priority}}</b></p>
                        <p><b>{{i.date}}</b></p>
                        <a class="btn btn-primary" href="{% url 'todoapp:update' i.id %}">update</a>
                        <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">delete</a>
                    </div>
                        </div>
                </div>
                <br>
               {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}

tasktodo/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update</div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">confirm</button>

           </form>
        </div>
    </div>
</div>
{% endblock %}